### ISSUE TITLE
Web Wrapper: support taking a YAML file or url in the scaffolding CLI

### ISSUE THREAD

**Issue by daniellacosse** [Jigsaw-Code/outline-sdk#435]
Currently in the scaffolding CLI you can only specify the smart dialer config via a compressed JSON string, which is really tough to reason about and generate. Adding support to the scaffolding CLI for loading a file containing the smart dialer YAML config would make it much easier to work with. Also it would be fairly easy to do.

**Comment by marceloomens** [comment]
I suggest the following YAML structure to begin with, based on the currently available configuration options and their defaults:

```YAML
platform: android
entryUrl: https://www.example.com
appName: 
appId: 
output: output
additionalDomains:
    - 
    - 
    - 
smartDialerConfig:
    dns:
        - https:
            name: 9.9.9.9
    tls:
        -
        - split:1
        - split:2
        - tlsfrag:1
```

- The following fields would be required: `platform`, `entryUrl`.
- The following fields have defaults: `outputs`, `smartDialerConfig`. The defaults are as specified in the code block above.

`appName`, `appId`, `additionalDomains` may be set from the response headers and the response body of a request made to `manifest.json` at `entryUrl`, if possible.

In any case, I suggest an order of priority as follows:

(1) cmd arguments > (2) YAML configuration > (3) manifest.json

What do you think?
